### PR TITLE
add 1.19.4 support

### LINKED ISSUE #191: 1.19.4 comaptibility
When I start the plugin on 1.19.4 it spam errors in console
image

### PR DESCRIPTION
**Pull request by mind04**
Add 1.19.4 support

closes #191

### CODE REVIEW

**Comment by FrankHeijden** [comment]
Thanks, looks good! I will do a final check tomorrow and release after :)

**Comment by SnickoDeadMC** [comment]
Still waiting to be merged?

**Comment by Izanaagii** [comment]
When 1.19.4 support is released ? Still waiting bro

**Comment by Izanaagii** [comment]
A few moments later...

**Comment by trainphreak** [comment]
This doesn't build from Paper 1.19 #499 onward, due to https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/1fddefce1cdce44010927b888432bf70c0e88cde#src/main/java/org/bukkit/craftbukkit/CraftChunk.java being pulled in from upstream

**Comment by Izanaagii** [comment]
Are you dead or ???

**Comment by Izanaagii** [comment]
If you upload it before sunday I'll pay you $5

**Comment by 4drian3d** [comment]
> Are you dead or ???

This is an open source project, anyone is able to make their own fork and upgrade to a new version. The author is not obliged to update it constantly (also indicated in the license)

**Comment by Izanaagii** [comment]
When 1.19.4 ???

**Comment by Izanaagii** [comment]
I'm not familiar with Github, how et where can I download 1.19.4 support so?

**Comment by 4drian3d** [comment]
> I'm not familiar with Github, how et where can I download 1.19.4 support so?

https://modrinth.com/plugin/insights/version/6.14.1

**Comment by Izanaagii** [comment]
So 1.19.4 not working, please fix it thanks!
Capture d'écran 2023-04-21 092009

**Comment by trainphreak** [comment]
Please open a new GitHub issue for that, this issue is specific to adding
basic support for 1.19.4 and was closed days ago. You're only getting
replies because some people didn't unsubscribe for the notifications on it.

**Pull request merged**
